version: "3.8"

services:
  postgres:
    image: postgres
    container_name: cordon-container
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: moiKarmel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
